name: priors

channels:
    - conda-forge

dependencies:
  - pip
  - pip:
    - tensorflow
    - dtreeviz
    - lrcurve
    - tensorflow-lattice
    - pydot
  - python=3.8
  - scikit-learn
  - pandas
  - seaborn
  - jupyter
  - notebook
  - numpy
  - matplotlib